insert into camps (id, name) values (1, $$10th Planet Jiu-Jitsu$$);
insert into camps (id, name) values (2, $$Alliance Center$$);
insert into camps (id, name) values (3, $$AMC Pankration$$);
insert into camps (id, name) values (4, $$American Kickboxing Academy$$);
insert into camps (id, name) values (5, $$American Top Team$$);
insert into camps (id, name) values (6, $$Arizona Combat Sports$$);
insert into camps (id, name) values (7, $$Brazilian Top Team$$);
insert into camps (id, name) values (8, $$Cesar Gracie Jiu-Jitsu$$);
insert into camps (id, name) values (9, $$Extreme MMA$$);
insert into camps (id, name) values (10, $$Greg Jackson's Gym$$);
insert into camps (id, name) values (11, $$Minnesota Martial Arts Academy$$);
insert into camps (id, name) values (12, $$Rough House$$);
insert into camps (id, name) values (13, $$Serra Jiu-Jitsu$$);
insert into camps (id, name) values (14, $$Sityodtong$$);
insert into camps (id, name) values (15, $$Team Blackhouse$$);
insert into camps (id, name) values (16, $$Team Higashi$$);
insert into camps (id, name) values (17, $$Team Link$$);
insert into camps (id, name) values (18, $$Team Militant$$);
insert into camps (id, name) values (19, $$Team Penn$$);
insert into camps (id, name) values (20, $$Team Punishment$$);
insert into camps (id, name) values (21, $$Team Quest$$);
insert into camps (id, name) values (22, $$Team Tompkins$$);
insert into camps (id, name) values (23, $$The Arena$$);
insert into camps (id, name) values (24, $$The HIT Squad$$);
insert into camps (id, name) values (25, $$The Pit$$);
insert into camps (id, name) values (26, $$Wolfslair MMA Academy$$);
insert into camps (id, name) values (27, $$Zahabi MMA$$);
