insert into fighters (weightclass, country, name, nickname, record) values (1, $$United States of America$$, $$Urijah Faber*$$, $$California Kid !The California Kid$$, $$9–4$$);
insert into fighters (weightclass, country, name, nickname, record) values (1, $$United States of America$$, $$Scott Jorgensen*$$, $$Young Guns$$, $$8–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (1, $$United States of America$$, $$Miguel Angel Torres*$$, $$z$$, $$7–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (1, $$United States of America$$, $$Dominick Cruz* (C)$$, $$Dominator$$, $$8–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (1, $$United States of America$$, $$Brian Bowles*$$, $$z$$, $$7–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (1, $$United States of America$$, $$Joseph Benavidez*$$, $$Joe-B-Wan Kenobi$$, $$6–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (1, $$United States of America$$, $$Eddie Wineland*$$, $$z$$, $$5–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (1, $$Japan$$, $$Takeya Mizugaki*$$, $$z$$, $$3–4$$);
insert into fighters (weightclass, country, name, nickname, record) values (1, $$Brazil$$, $$Raphael Assunção$$, $$z$$, $$3–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (1, $$United States of America$$, $$Damacio Page*$$, $$Angel of Death !The Angel of Death$$, $$3–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (1, $$United States of America$$, $$Jeff Curran*$$, $$Big Frog$$, $$1–5$$);
insert into fighters (weightclass, country, name, nickname, record) values (1, $$United States of America$$, $$Demetrious Johnson*$$, $$Mighty Mouse$$, $$4–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (1, $$England$$, $$Brad Pickett*$$, $$One-Punch$$, $$3–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (1, $$United States of America$$, $$Chris Cariaso*$$, $$Kamikaze$$, $$2–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (1, $$El Salvador$$, $$Ivan Menjivar*$$, $$Pride of El Salvador$$, $$2–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (1, $$Haiti$$, $$Yves Jabouin$$, $$Tiger$$, $$1–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (1, $$Brazil$$, $$Renan Barão*$$, $$Barão$$, $$3–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (1, $$United States of America$$, $$Michael McDonald*$$, $$Mayday$$, $$3–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (1, $$United States of America$$, $$Nick Pace*$$, $$z$$, $$1–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (1, $$United States of America$$, $$Reuben Duran$$, $$Hurricane$$, $$1–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (1, $$United States of America$$, $$Ian Loveland$$, $$Barn Owl !The Barn Owl$$, $$1–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (1, $$United States of America$$, $$Jason Reinhardt$$, $$z$$, $$0–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (1, $$United States of America$$, $$Ken Stone*$$, $$z$$, $$0–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (1, $$United States of America$$, $$Jeff Hougland$$, $$Hellbound$$, $$1–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (1, $$United States of America$$, $$Cole Escovedo$$, $$Apache Kid$$, $$0–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (1, $$United States of America$$, $$Edwin Figueroa$$, $$Feroz !El Feroz$$, $$0–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (1, $$United States of America$$, $$Donny Walker$$, $$Eagle Eye$$, $$0–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (1, $$Japan$$, $$Norifumi Yamamoto$$, $$Kid$$, $$0–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (1, $$United States of America$$, $$Mike Easton$$, $$Hulk !The Hulk$$, $$0–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (1, $$Brazil$$, $$Johnny Eduardo$$, $$z$$, $$0–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (1, $$England$$, $$Vaughan Lee$$, $$z$$, $$0–0$$);
