insert into fighters (weightclass, country, name, nickname, record) values (2, $$United States of America$$, $$Kenny Florian$$, $$KenFlo$$, $$12–4$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$United States of America$$, $$Tyson Griffin$$, $$z$$, $$8–5$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$United States of America$$, $$Leonard Garcia*$$, $$Bad Boy$$, $$6–6–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$United States of America$$, $$Mike Brown*$$, $$z$$, $$7–5$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$Armenia$$, $$Manny Gamburyan*$$, $$Anvil !The Anvil$$, $$5–5$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$Brazil$$, $$José Aldo* (C)$$, $$Junior$$, $$9–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$Canada$$, $$Mark Hominick*$$, $$Machine !The Machine$$, $$6–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$Brazil$$, $$Rani Yahya*$$, $$z$$, $$5–4$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$United States of America$$, $$Cub Swanson*$$, $$Cub$$, $$5–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$United States of America$$, $$George Roop*$$, $$z$$, $$3–4–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$United States of America$$, $$Ricardo Lamas*$$, $$Bully !The Bully$$, $$5–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$Brazil$$, $$Diego Nunes*$$, $$Gun !The Gun$$, $$5–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$Poland$$, $$Bart Palaszewski$$, $$Bartimus$$, $$4–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$United States of America$$, $$Chad Mendes*$$, $$Money$$, $$6–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$United States of America$$, $$Josh Grispi*$$, $$Fluke !The Fluke$$, $$4–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$Cuba$$, $$Javier Vazquez*$$, $$Showtime$$, $$3–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$United States of America$$, $$Erik Koch*$$, $$New Breed$$, $$4–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$United States of America$$, $$Mackens Semerzier*$$, $$Menace !da Menace$$, $$2–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$United States of America$$, $$Matt Grice$$, $$Real One !The Real One$$, $$1–4$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$United States of America$$, $$Dustin Poirier*$$, $$Diamond !The Diamond$$, $$3–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$Japan$$, $$Michihiro Omigawa$$, $$z$$, $$0–4$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$United States of America$$, $$Darren Elkins$$, $$Damage !The Damage$$, $$2–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$United States of America$$, $$Pablo Garza*$$, $$Scarecrow !The Scarecrow$$, $$2–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$China$$, $$Tiequan Zhang*$$, $$Mongolian Wolf !The Mongolian Wolf$$, $$2–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$South Korea$$, $$Chan Sung Jung*$$, $$Korean Zombie !The Korean Zombie$$, $$1–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$United States of America$$, $$Jonathan Brookins$$, $$z$$, $$1–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$United States of America$$, $$Nam Phan$$, $$z$$, $$0–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$Brazil$$, $$Yuri Alcantara*$$, $$Marajó$$, $$1–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$United States of America$$, $$Alex Caceres$$, $$Bruce Leroy$$, $$0–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$United States of America$$, $$Mike Lullo$$, $$z$$, $$0–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$England$$, $$Jason Young$$, $$Shotgun$$, $$0–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$Brazil$$, $$Felipe Arantes$$, $$Sertanejo$$, $$0–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$Canada$$, $$Antonio Carvalho$$, $$Pato$$, $$0–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$United States of America$$, $$Jimy Hettes$$, $$The Kid$$, $$0–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (2, $$Japan$$, $$Hatsu Hioki$$, $$Iron Broom$$, $$0–0$$);
