insert into fighters (weightclass, country, name, nickname, record) values (7, $$United States of America$$, $$Frank Mir$$, $$z$$, $$13–5$$);
insert into fighters (weightclass, country, name, nickname, record) values (7, $$France$$, $$Cheick Kongo$$, $$Kongo$$, $$9–4–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (7, $$Croatia$$, $$Mirko Cro Cop$$, $$Cro Cop$$, $$4–5$$);
insert into fighters (weightclass, country, name, nickname, record) values (7, $$Netherlands$$, $$Stefan Struve$$, $$Skyscraper$$, $$5–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (7, $$Brazil$$, $$Junior Dos Santos$$, $$Cigano$$, $$7–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (7, $$United States of America$$, $$Cain Velasquez (C)$$, $$z$$, $$7–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (7, $$United States of America$$, $$Shane Carwin$$, $$Engineer !The Engineer$$, $$4–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (7, $$United States of America$$, $$Brock Lesnar$$, $$z$$, $$4–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (7, $$United States of America$$, $$Pat Barry$$, $$HD$$, $$3–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (7, $$United States of America$$, $$Matt Mitrione$$, $$Meathead$$, $$5–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (7, $$United States of America$$, $$Brendan Schaub$$, $$Hybrid !The Hybrid$$, $$4–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (7, $$United States of America$$, $$Joey Beltran$$, $$Mexicutioner !The Mexicutioner$$, $$3–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (7, $$Brazil$$, $$Minotauro Nogueira$$, $$Minotauro$$, $$3–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (7, $$United States of America$$, $$Heath Herring$$, $$Texas Crazy Horse !The Texas Crazy Horse$$, $$2–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (7, $$United States of America$$, $$Roy Nelson$$, $$Big Country$$, $$2–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (7, $$United States of America$$, $$Mike Russow$$, $$z$$, $$3–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (7, $$United States of America$$, $$Travis Browne$$, $$Hapa$$, $$2–0–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (7, $$United States of America$$, $$Christian Morecraft$$, $$z$$, $$1–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (7, $$New Zealand$$, $$Mark Hunt$$, $$Super Samoan$$, $$1–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (7, $$United States of America$$, $$Ben Rothwell$$, $$Big$$, $$1–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (7, $$England$$, $$Rob Broughton$$, $$Bear !The Bear$$, $$1–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (7, $$United States of America$$, $$Dave Herman$$, $$Pee-Wee$$, $$1–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (7, $$United States of America$$, $$Aaron Rosa$$, $$Big Red$$, $$0–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (7, $$England$$, $$Philip De Fries<sup id="cite_ref-16" class="reference">[11]</sup>$$, $$z$$, $$0–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (7, $$United States of America$$, $$Stipe Miocic$$, $$z$$, $$0–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (7, $$England$$, $$Oli Thompson<sup id="cite_ref-brits_17-0" class="reference">[12]</sup>$$, $$z$$, $$0–0$$);
