insert into fighters (weightclass, country, name, nickname, record) values (3, $$United States of America$$, $$Melvin Guillard$$, $$Young Assassin !The Young Assassin$$, $$10–4$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$United States of America$$, $$Clay Guida$$, $$Carpenter !The Carpenter$$, $$9–5$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$Brazil$$, $$Gleison Tibau$$, $$Tibau$$, $$9–5$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$United States of America$$, $$Nate Diaz$$, $$z$$, $$8–5$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$Bahamas$$, $$Yves Edwards$$, $$Thugjitsu Master$$, $$8–5$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$United States of America$$, $$Spencer Fisher$$, $$King !The King$$, $$7–6$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$United States of America$$, $$Donald Cerrone*$$, $$Cowboy !The Cowboy$$, $$8–3 (1 NC)$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$United States of America$$, $$Sean Sherk$$, $$Muscle Shark !The Muscle Shark$$, $$8–4$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$Russia$$, $$Dennis Siver$$, $$z$$, $$8–4$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$United States of America$$, $$Jeremy Stephens$$, $$Lil' Heathen$$, $$7–5$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$United States of America$$, $$Matt Wiman$$, $$Handsome$$, $$7–4$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$Canada$$, $$Sam Stout$$, $$Hands of Stone$$, $$6–5$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$United States of America$$, $$Jim Miller$$, $$z$$, $$9–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$United States of America$$, $$Gray Maynard$$, $$Bully !The Bully$$, $$8–0–1 (1 NC)$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$United States of America$$, $$Frankie Edgar (C)$$, $$Answer !The Answer$$, $$8–1–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$United States of America$$, $$Joe Lauzon$$, $$J-Lau$$, $$7–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$United States of America$$, $$Shane Roller*$$, $$z$$, $$7–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$Nigeria$$, $$Anthony Njokuani*$$, $$Assassin !The Assassin$$, $$6–4$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$Brazil$$, $$Thiago Tavares$$, $$z$$, $$5–4–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$Australia$$, $$George Sotiropoulos$$, $$z$$, $$7–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$United States of America$$, $$Danny Castillo*$$, $$Last Call$$, $$6–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$United States of America$$, $$Cole Miller$$, $$Magrinho$$, $$6–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$Canada$$, $$Mark Bocek$$, $$z$$, $$5–4$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$United States of America$$, $$Mac Danzig$$, $$z$$, $$4–5$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$England$$, $$Paul Taylor$$, $$Relentless$$, $$4–5$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$England$$, $$Terry Etim$$, $$z$$, $$5–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$United States of America$$, $$Ben Henderson*$$, $$Smooth$$, $$6–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$United States of America$$, $$Nik Lentz$$, $$Carny !The Carny$$, $$5–0–1 (1 NC)$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$United States of America$$, $$Anthony Pettis*$$, $$Showtime$$, $$5–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$Brazil$$, $$Rafael Dos Anjos$$, $$z$$, $$4–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$United States of America$$, $$Aaron Riley$$, $$z$$, $$3–4$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$United States of America$$, $$Evan Dunham$$, $$Three D3-D$$, $$4–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$Canada$$, $$TJ Grant$$, $$z$$, $$3–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$England$$, $$Ross Pearson$$, $$Real Deal !The Real Deal$$, $$4–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$Iran$$, $$Kamal Shalorus*$$, $$Prince of Persia$$, $$3–1–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$United States of America$$, $$Jacob Volkmann$$, $$Christmas$$, $$3–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$Brazil$$, $$Charles Oliveira$$, $$Bronx !do Bronx$$, $$2–1 (1 NC)$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$Brazil$$, $$Rafaello Oliveira$$, $$Tractor$$, $$1–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$United States of America$$, $$Dan Downes*$$, $$Danny Boy$$, $$1–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$Japan$$, $$Takanori Gomi$$, $$Fireball Kid !The Fireball Kid$$, $$1–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$Brazil$$, $$Edson Barboza$$, $$Junior$$, $$2–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$Canada$$, $$John Makdessi$$, $$Bull !The Bull$$, $$2–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$United States of America$$, $$Michael Johnson$$, $$Menace !The Menace$$, $$1–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$United States of America$$, $$Cody McKenzie$$, $$Big Time$$, $$1–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$United States of America$$, $$Edward Faaloloto*$$, $$FaloFalo$$, $$0–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$United States of America$$, $$Tony Ferguson$$, $$Cucuy !El Cucuy$$, $$1–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$England$$, $$Paul Sass$$, $$Sassangle$$, $$1–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$United States of America$$, $$Ramsey Nijem$$, $$z$$, $$0–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$United States of America$$, $$T.J. O'Brien$$, $$Spider !The Spider$$, $$0–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (3, $$Brazil$$, $$Vagner Rocha$$, $$z$$, $$0–1$$);
