insert into fighters (weightclass, country, name, nickname, record) values (6, $$United States of America$$, $$Tito Ortiz$$, $$Huntington Beach Bad Boy !The Huntington Beach Bad Boy$$, $$15–9–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (6, $$United States of America$$, $$Rich Franklin$$, $$Ace$$, $$13–5$$);
insert into fighters (weightclass, country, name, nickname, record) values (6, $$United States of America$$, $$Rashad Evans$$, $$Suga$$, $$11–1–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (6, $$United States of America$$, $$Forrest Griffin$$, $$z$$, $$9–4$$);
insert into fighters (weightclass, country, name, nickname, record) values (6, $$United States of America$$, $$Brandon Vera$$, $$Truth !The Truth$$, $$7–5 (1 NC)$$);
insert into fighters (weightclass, country, name, nickname, record) values (6, $$United States of America$$, $$Stephan Bonnar$$, $$American Psycho !The American Psycho$$, $$7–6$$);
insert into fighters (weightclass, country, name, nickname, record) values (6, $$Brazil$$, $$Lyoto Machida$$, $$Dragon !The Dragon$$, $$9–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (6, $$Belarus$$, $$Vladimir Matyushenko$$, $$Janitor !The Janitor$$, $$7–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (6, $$United States of America$$, $$Rampage Jackson$$, $$Rampage$$, $$7–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (6, $$United States of America$$, $$Jon Jones (C)$$, $$Bones$$, $$7–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (6, $$Poland$$, $$Krzysztof Soszynski$$, $$Polish Experiment !The Polish Experiment$$, $$6–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (6, $$Brazil$$, $$Thiago Silva$$, $$z$$, $$5–2 (1 NC)$$);
insert into fighters (weightclass, country, name, nickname, record) values (6, $$United States of America$$, $$Ryan Bader$$, $$Darth$$, $$5–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (6, $$Brazil$$, $$Luiz Cane$$, $$Banha$$, $$4–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (6, $$United States of America$$, $$Jason Brilz$$, $$Hitman !The Hitman$$, $$3–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (6, $$Brazil$$, $$Mauricio Rua$$, $$Shogun$$, $$3–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (6, $$United States of America$$, $$Phil Davis$$, $$Mr. Wonderful$$, $$5–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (6, $$Sweden$$, $$Alexander Gustafsson$$, $$Mauler !The Mauler$$, $$4–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (6, $$United States of America$$, $$Kyle Kingsbury$$, $$Kingsbu$$, $$4–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (6, $$United States of America$$, $$Eliot Marshall$$, $$Fire !The Fire$$, $$3–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (6, $$Croatia$$, $$Igor Pokrajac$$, $$Duke !The Duke$$, $$2–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (6, $$Brazil$$, $$Antonio Rogerio Nogueira$$, $$Little Nog$$, $$2–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (6, $$Australia$$, $$Anthony Perosh$$, $$Hippo !The Hippo$$, $$1–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (6, $$France$$, $$Cyrille Diabate$$, $$Snake !The Snake$$, $$2–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (6, $$Brazil$$, $$Fabio Maldonado$$, $$z$$, $$1–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (6, $$United States of America$$, $$Ricardo Romero$$, $$z$$, $$1–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (6, $$New Zealand$$, $$James Te Huna$$, $$z$$, $$1–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (6, $$Czech Republic$$, $$Karlos Vemola$$, $$Terminator !The Terminator$$, $$1–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (6, $$Brazil$$, $$Ronny Markes$$, $$Markes$$, $$0–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (6, $$Bulgaria$$, $$Stanislav Nedkov$$, $$Staki$$, $$0–0$$);
