insert into fighters (weightclass, country, name, nickname, record) values (5, $$United States of America$$, $$Chris Leben$$, $$The Crippler$$, $$12–6$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$England$$, $$Michael Bisping$$, $$The Count$$, $$11–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$Brazil$$, $$Vitor Belfort$$, $$The Phenom$$, $$9–5$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$United States of America$$, $$Jorge Rivera$$, $$El Conquistador$$, $$7–7$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$Brazil$$, $$Anderson Silva (C)$$, $$The Spider$$, $$13–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$Brazil$$, $$Royce Gracie$$, $$z$$, $$11–1–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$Japan$$, $$Yushin Okami$$, $$Thunder$$, $$10–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$United States of America$$, $$Brian Stann*$$, $$All American$$, $$9–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$Italy$$, $$Alessio Sakara$$, $$Legionarius$$, $$6–5 (1 NC)$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$Canada$$, $$Jason MacDonald$$, $$The Athlete$$, $$6–6$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$Brazil$$, $$Demian Maia$$, $$z$$, $$8–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$United States of America$$, $$Alan Belcher$$, $$The Talent$$, $$7–4$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$United States of America$$, $$Chael Sonnen*$$, $$z$$, $$6–5$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$United States of America$$, $$Mark Muñoz*$$, $$The Filipino Wrecking Machine$$, $$8–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$United States of America$$, $$Nate Quarry$$, $$Rock$$, $$7–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$United States of America$$, $$Ed Herman$$, $$Short Fuse$$, $$5–5$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$United States of America$$, $$Dan Miller$$, $$z$$, $$5–4$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$Brazil$$, $$Wanderlei Silva$$, $$The Axe Murderer$$, $$3–6$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$United States of America$$, $$Aaron Simpson*$$, $$A-Train$$, $$6–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$United States of America$$, $$C.B. Dollaway$$, $$The Doberman$$, $$5–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$United States of America$$, $$Steve Cantwell$$, $$The Robot$$, $$4–4$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$Brazil$$, $$Rousimar Palhares$$, $$Toquinho$$, $$5–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$United States of America$$, $$Tim Boetsch$$, $$The Barbarian$$, $$4–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$United States of America$$, $$Nick Catone$$, $$The Jersey Devil$$, $$3–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$United States of America$$, $$Tim Credeur$$, $$Crazy$$, $$3–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$United States of America$$, $$Tom Lawlor$$, $$Filthy$$, $$3–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$Japan$$, $$Yoshihiro Akiyama$$, $$Sexyama$$, $$1–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$United States of America$$, $$Mike Massenzio$$, $$The Master of Disaster$$, $$1–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$Brazil$$, $$Jorge Santiago$$, $$The Sandman$$, $$1–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$Australia$$, $$Kyle Noke$$, $$KO$$, $$3–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$United States of America$$, $$Brad Tavares$$, $$z$$, $$2–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$Brazil$$, $$Rafael Natal$$, $$Sapo$$, $$1–1–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$United States of America$$, $$Jared Hamman$$, $$The Messenger$$, $$1–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$United States of America$$, $$Court McGee$$, $$The Crusher$$, $$2–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$Canada$$, $$Nick Ring$$, $$The Promise$$, $$2–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$United States of America$$, $$Chris Weidman$$, $$The All-American$$, $$2–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$United States of America$$, $$Jason Miller*$$, $$Mayhem$$, $$1–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$Cyprus$$, $$Constantinos Philippou$$, $$Costa$$, $$1–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$South Korea$$, $$Dongi Yang$$, $$The Ox$$, $$1–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$United States of America$$, $$Paul Bradley$$, $$The Gentleman$$, $$0–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (5, $$Japan$$, $$Riki Fukuda$$, $$Killer Bee$$, $$0–1$$);
