insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$Matt Hughes$$, $$z$$, $$18–6$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$B.J. Penn$$, $$Prodigy !The Prodigy$$, $$12–6–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$Chris Lytle$$, $$Lights Out$$, $$9–10$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$Canada$$, $$Georges St-Pierre (C)$$, $$Rush$$, $$16–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$Josh Koscheck$$, $$Kos$$, $$13–5$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$Diego Sanchez$$, $$Dream !The Dream$$, $$12–4$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$Jon Fitch$$, $$z$$, $$13–1–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$Brazil$$, $$Thiago Alves$$, $$Pitbull$$, $$10–5$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$Matt Serra$$, $$Terror !The Terror$$, $$7–7$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$Mike Swick$$, $$Quick$$, $$9–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$Denmark$$, $$Martin Kampmann$$, $$Hitman$$, $$8–4$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$Carlos Condit*$$, $$Natural Born Killer !The Natural Born Killer$$, $$9–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$Nick Diaz$$, $$z$$, $$6–4$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$Johny Hendricks*$$, $$z$$, $$8–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$Anthony Johnson$$, $$Rumble$$, $$6–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$Matt Brown$$, $$Immortal !The Immortal$$, $$5–4$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$Rick Story$$, $$Horror !The Horror$$, $$6–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$Dennis Hallman$$, $$Superman$$, $$3–5$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$South Korea$$, $$Dong Hyun Kim$$, $$Stun Gun$$, $$5–1 (1 NC)$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$Matthew Riddle$$, $$z$$, $$5–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$Amir Sadollah$$, $$z$$, $$5–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$England$$, $$Dan Hardy$$, $$Outlaw !The Outlaw$$, $$4–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$Mike Pyle$$, $$Quicksand$$, $$4–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$England$$, $$John Hathaway$$, $$Hitman !The Hitman$$, $$5–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$Mike Pierce$$, $$z$$, $$4–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$DaMarques Johnson$$, $$Darkness$$, $$3–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$Daniel Roberts$$, $$Ninja$$, $$3–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$Brazil$$, $$Paulo Thiago$$, $$z$$, $$3–3$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$Jake Ellenberger$$, $$Juggernaut !The Juggernaut$$, $$4–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$Brian Foster$$, $$Foster Boy !The Foster Boy$$, $$3–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$Duane Ludwig$$, $$Bang$$, $$3–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$Rich Attonito$$, $$Raging Bull !The Raging Bull$$, $$3–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$Charlie Brenneman$$, $$Spaniard !The Spaniard$$, $$3–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$Canada$$, $$Rory MacDonald$$, $$Ares$$, $$3–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$England$$, $$James Wilks$$, $$Lightning$$, $$2–2$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$Canada$$, $$Claude Patrick$$, $$Prince !The Prince$$, $$3–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$Brian Ebersole$$, $$Bad Boy$$, $$2–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$Canada$$, $$Sean Pierson$$, $$Pimp Daddy$$, $$1–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$Brazil$$, $$Carlos Eduardo Rocha$$, $$Danado !Ta Danado$$, $$1–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$Jake Shields$$, $$z$$, $$1–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$TJ Waldburger$$, $$TJ$$, $$1–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$Shamar Bailey$$, $$z$$, $$1–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$Chris Cope$$, $$C-Murder$$, $$1–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$Clay Harvison$$, $$Heavy Metal$$, $$1–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$Germany$$, $$Pascal Krauss$$, $$Panzer$$, $$1–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$Justin Edwards$$, $$Fast Eddie$$, $$0–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$James Head$$, $$z$$, $$0–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$David Mitchell$$, $$Daudi$$, $$0–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$England$$, $$Mark Scanlon$$, $$Scanno$$, $$0–1$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$Sweden$$, $$Papy Abedi$$, $$Makambo$$, $$0–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$Lance Benoist$$, $$z$$, $$0–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$United States of America$$, $$Jorge Lopez$$, $$Lil' Monster$$, $$0–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$England$$, $$Che Mills$$, $$z$$, $$0–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$Bazil$$, $$Luis Ramos$$, $$Beicao$$, $$0–0$$);
insert into fighters (weightclass, country, name, nickname, record) values (4, $$Brazil$$, $$Erick Silva$$, $$Indio$$, $$0–0$$);
