insert into moves (id,name,reqstring) values (1, $$German Suplex to Back Side Control Offense$$, $$Suplex to Side Control Offense$$);
insert into moves (id,name,reqstring) values (2, $$Lift Up Slam to Side Control Offense$$, $$None$$);
insert into moves (id,name,reqstring) values (3, $$Pummel to Double Underhook Defense$$, $$None$$);
insert into moves (id,name,reqstring) values (4, $$Transition to Both Standing$$, $$None$$);
insert into moves (id,name,reqstring) values (5, $$Back Throw to Side Control Right Offense$$, $$None$$);
insert into moves (id,name,reqstring) values (6, $$German Suplex to Back Side Control Offense$$, $$Suplex to Side Control Offense$$);
insert into moves (id,name,reqstring) values (7, $$Pull to Side Control$$, $$None$$);
insert into moves (id,name,reqstring) values (8, $$Transition to Both Standing$$, $$None$$);
insert into moves (id,name,reqstring) values (9, $$Arm Trap Rear Naked Choke$$, $$Submission Offense of 60$$);
insert into moves (id,name,reqstring) values (10, $$Armbar from Back Mount Face Up Top$$, $$None$$);
insert into moves (id,name,reqstring) values (11, $$Rear Naked Choke$$, $$None$$);
insert into moves (id,name,reqstring) values (12, $$Strong Right Hook$$, $$None$$);
insert into moves (id,name,reqstring) values (13, $$Transition to Back Mount Face Up Body Triangle Top$$, $$None$$);
insert into moves (id,name,reqstring) values (14, $$Transition to Mount Top$$, $$None$$);
insert into moves (id,name,reqstring) values (15, $$Rear Naked Choke from Back Mount Rocked$$, $$None$$);
insert into moves (id,name,reqstring) values (16, $$Arm Trap Rear Naked Choke$$, $$Submission Offense of 60$$);
insert into moves (id,name,reqstring) values (17, $$Armbar from Back Mount Top$$, $$None$$);
insert into moves (id,name,reqstring) values (18, $$Rear Naked Choke Facing Downward$$, $$None$$);
insert into moves (id,name,reqstring) values (19, $$Strong Hook$$, $$None$$);
insert into moves (id,name,reqstring) values (20, $$Transition to Both Standing$$, $$None$$);
insert into moves (id,name,reqstring) values (21, $$Transition to Open Guard Bottom$$, $$None$$);
insert into moves (id,name,reqstring) values (22, $$Arm Trap Rear Naked Choke$$, $$Submission Offense of 60$$);
insert into moves (id,name,reqstring) values (23, $$Rear Naked Choke$$, $$None$$);
insert into moves (id,name,reqstring) values (24, $$Arm Trap Rear Naked Choke$$, $$Submission Offense of 60$$);
insert into moves (id,name,reqstring) values (25, $$Armbar from Back Side Control Top$$, $$None$$);
insert into moves (id,name,reqstring) values (26, $$Peruvian Neck Tie$$, $$Submission Offense of 60$$);
insert into moves (id,name,reqstring) values (27, $$Rear Naked Choke$$, $$None$$);
insert into moves (id,name,reqstring) values (28, $$Strong Hook$$, $$None$$);
insert into moves (id,name,reqstring) values (29, $$Strong Knee to Abdomen$$, $$None$$);
insert into moves (id,name,reqstring) values (30, $$Transition to Back Mount Face Up Top$$, $$None$$);
insert into moves (id,name,reqstring) values (31, $$Transition to Back Mount Top$$, $$None$$);
insert into moves (id,name,reqstring) values (32, $$Pull Guard to Open Guard Down Defense$$, $$Clinch to Body Lock Offense$$);
insert into moves (id,name,reqstring) values (33, $$Suplex to Side Control Offense$$, $$Clinch to Body Lock Offense$$);
insert into moves (id,name,reqstring) values (34, $$Judo Hip Throw to Side Control Offense$$, $$Clinch to Body Lock Offense$$);
insert into moves (id,name,reqstring) values (35, $$Pull Guard to Open Guard Down Defense$$, $$Clinch to Body Lock Offense$$);
insert into moves (id,name,reqstring) values (36, $$Suplex to Half Guard Down Offense$$, $$Clinch to Body Lock Offense$$);
insert into moves (id,name,reqstring) values (37, $$Suplex to Side Control Offense$$, $$Clinch to Body Lock Offense$$);
insert into moves (id,name,reqstring) values (38, $$Inside Left Uppercut$$, $$None$$);
insert into moves (id,name,reqstring) values (39, $$Inside Right Uppercut$$, $$None$$);
insert into moves (id,name,reqstring) values (40, $$Left Leg Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (41, $$Left Muay Thai Elbow$$, $$None$$);
insert into moves (id,name,reqstring) values (42, $$Left Short Uppercut From Sway Forward$$, $$None$$);
insert into moves (id,name,reqstring) values (43, $$Right Chopping Hook$$, $$None$$);
insert into moves (id,name,reqstring) values (44, $$Right Dodge Knee to the Body$$, $$None$$);
insert into moves (id,name,reqstring) values (45, $$Right Leg Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (46, $$Right Muay Thai Elbow$$, $$None$$);
insert into moves (id,name,reqstring) values (47, $$Right Short Uppercut from Sway Forward$$, $$None$$);
insert into moves (id,name,reqstring) values (48, $$Strong Left Leg Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (49, $$Strong Right Leg Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (50, $$Backstep Right Hook from Switch Stance$$, $$None$$);
insert into moves (id,name,reqstring) values (51, $$Backstepping Right Straight$$, $$None$$);
insert into moves (id,name,reqstring) values (52, $$Brock's Right Straight$$, $$None$$);
insert into moves (id,name,reqstring) values (53, $$Caol's Back Spin Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (54, $$Caol's Left Side Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (55, $$Check Head Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (56, $$Chuck's Right Straight$$, $$None$$);
insert into moves (id,name,reqstring) values (57, $$Ducking Left Hook$$, $$None$$);
insert into moves (id,name,reqstring) values (58, $$Ducking Right Hook$$, $$None$$);
insert into moves (id,name,reqstring) values (59, $$Forrest's Left Front Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (60, $$Forrest's Left Head Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (61, $$GSP's Head Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (62, $$Hendo's Right Back Fist$$, $$None$$);
insert into moves (id,name,reqstring) values (63, $$Hendo's Right Strong Straight$$, $$None$$);
insert into moves (id,name,reqstring) values (64, $$Jardine's Right Superman Punch$$, $$None$$);
insert into moves (id,name,reqstring) values (65, $$Jon Jones' Right Back Fist$$, $$None$$);
insert into moves (id,name,reqstring) values (66, $$Left Axe Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (67, $$Left Back Fist$$, $$None$$);
insert into moves (id,name,reqstring) values (68, $$Left Front Upward Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (69, $$Left Flicking Jab$$, $$None$$);
insert into moves (id,name,reqstring) values (70, $$Left Guarded Hook$$, $$None$$);
insert into moves (id,name,reqstring) values (71, $$Left Head Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (72, $$Left High Front Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (73, $$Left Hook from Sway Back$$, $$None$$);
insert into moves (id,name,reqstring) values (74, $$Left Hook from Sway Forward$$, $$None$$);
insert into moves (id,name,reqstring) values (75, $$Left Hook from Sway Left$$, $$None$$);
insert into moves (id,name,reqstring) values (76, $$Left Hook from Sway Right$$, $$None$$);
insert into moves (id,name,reqstring) values (77, $$Left Jab to Sway Back$$, $$None$$);
insert into moves (id,name,reqstring) values (78, $$Left Jumping Front Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (79, $$Left Long Superman Punch$$, $$None$$);
insert into moves (id,name,reqstring) values (80, $$Left Muay Thai Head Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (81, $$Left Muay Thai Leg Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (82, $$Left Muay Thai Push Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (83, $$Left Over Hook$$, $$None$$);
insert into moves (id,name,reqstring) values (84, $$Left Over Strong Hook$$, $$None$$);
insert into moves (id,name,reqstring) values (85, $$Left Punch from Kick Catch$$, $$None$$);
insert into moves (id,name,reqstring) values (86, $$Left Quick Superman Punch$$, $$None$$);
insert into moves (id,name,reqstring) values (87, $$Left Side Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (88, $$Left Side Kick to Body$$, $$None$$);
insert into moves (id,name,reqstring) values (89, $$Left Sidestepping Upper Jab$$, $$None$$);
insert into moves (id,name,reqstring) values (90, $$Left Spinning Back Fist$$, $$None$$);
insert into moves (id,name,reqstring) values (91, $$Left Spinning Back Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (92, $$Left Strong Uppercut$$, $$None$$);
insert into moves (id,name,reqstring) values (93, $$Left Undercut$$, $$None$$);
insert into moves (id,name,reqstring) values (94, $$Left Upper Jab$$, $$None$$);
insert into moves (id,name,reqstring) values (95, $$Left Uppercut$$, $$None$$);
insert into moves (id,name,reqstring) values (96, $$Lunging Left Hook$$, $$None$$);
insert into moves (id,name,reqstring) values (97, $$Lunging Right Hook$$, $$None$$);
insert into moves (id,name,reqstring) values (98, $$Lyoto's Left Head Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (99, $$Lyoto's Right Straight$$, $$None$$);
insert into moves (id,name,reqstring) values (100, $$Lyoto's Stepping Straight$$, $$None$$);
insert into moves (id,name,reqstring) values (101, $$Napao's Right Head Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (102, $$One Feint Head Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (103, $$Overhand Left from Sway Forward$$, $$None$$);
insert into moves (id,name,reqstring) values (104, $$Overhand Right$$, $$None$$);
insert into moves (id,name,reqstring) values (105, $$Overhand Right from Sway Forward$$, $$None$$);
insert into moves (id,name,reqstring) values (106, $$Overhand Right Hook from Sway Forward$$, $$None$$);
insert into moves (id,name,reqstring) values (107, $$Quick Head Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (108, $$Right Axe Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (109, $$Right Back Fist$$, $$None$$);
insert into moves (id,name,reqstring) values (110, $$Right Back Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (111, $$Right Brazilian Head Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (112, $$Right Ducking Uppercut to Head$$, $$None$$);
insert into moves (id,name,reqstring) values (113, $$Right Flying Head Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (114, $$Right Flying Knee$$, $$None$$);
insert into moves (id,name,reqstring) values (115, $$Right Front Upper Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (116, $$Right Guarded Hook$$, $$None$$);
insert into moves (id,name,reqstring) values (117, $$Right Head Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (118, $$Right High Front Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (119, $$Right High Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (120, $$Right Hook from Sway Back$$, $$None$$);
insert into moves (id,name,reqstring) values (121, $$Right Hook from Sway Left$$, $$None$$);
insert into moves (id,name,reqstring) values (122, $$Right Hook From Sway Right$$, $$None$$);
insert into moves (id,name,reqstring) values (123, $$Right Karate Back Spin Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (124, $$Right Karate Front Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (125, $$Right Karate Straight$$, $$None$$);
insert into moves (id,name,reqstring) values (126, $$Right Long Straight$$, $$None$$);
insert into moves (id,name,reqstring) values (127, $$Right Long Superman Punch$$, $$None$$);
insert into moves (id,name,reqstring) values (128, $$Right Long Uppercut$$, $$None$$);
insert into moves (id,name,reqstring) values (129, $$Right Over Hook$$, $$None$$);
insert into moves (id,name,reqstring) values (130, $$Right MMA Back Spin Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (131, $$Right Muay Thai Head Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (132, $$Right Muay Thai Leg Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (133, $$Right Muay Thai Push Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (134, $$Right Muay Thai Snap Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (135, $$Right Punch from Kick Catch$$, $$None$$);
insert into moves (id,name,reqstring) values (136, $$Right Spinning Back Elbow$$, $$None$$);
insert into moves (id,name,reqstring) values (137, $$Right Spinning Back Fist$$, $$None$$);
insert into moves (id,name,reqstring) values (138, $$Right Spinning Back Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (139, $$Right Strong Straight$$, $$None$$);
insert into moves (id,name,reqstring) values (140, $$Right Strong Uppercut$$, $$None$$);
insert into moves (id,name,reqstring) values (141, $$Right Superman Punch$$, $$None$$);
insert into moves (id,name,reqstring) values (142, $$Right Uppercut$$, $$None$$);
insert into moves (id,name,reqstring) values (143, $$Shogun's Stepping Left Hook$$, $$None$$);
insert into moves (id,name,reqstring) values (144, $$Shoot to Double Leg Takedown$$, $$None$$);
insert into moves (id,name,reqstring) values (145, $$Step Right Knee$$, $$None$$);
insert into moves (id,name,reqstring) values (146, $$Stepping Heavy Jab$$, $$None$$);
insert into moves (id,name,reqstring) values (147, $$Stepping Over Left Hook$$, $$None$$);
insert into moves (id,name,reqstring) values (148, $$Stepping Right Undercut$$, $$None$$);
insert into moves (id,name,reqstring) values (149, $$Stepping Right Uppercut$$, $$None$$);
insert into moves (id,name,reqstring) values (150, $$Strong Left Leg Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (151, $$Strong Right Leg Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (152, $$Switch Left Head Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (153, $$Two Step Left Flying Knee$$, $$None$$);
insert into moves (id,name,reqstring) values (154, $$Two Step Right Flying Knee$$, $$None$$);
insert into moves (id,name,reqstring) values (155, $$Two Step Right Middle Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (156, $$Weaving Overhand Right$$, $$None$$);
insert into moves (id,name,reqstring) values (157, $$Gogoplata from Butterfly Guard$$, $$Transition to Butterfly Guard Bottom and Submission Offense 70$$);
insert into moves (id,name,reqstring) values (158, $$Transition to Open Guard Down Bottom$$, $$Transition to Butterfly Guard Bottom$$);
insert into moves (id,name,reqstring) values (159, $$Transition to Up/Down Bottom$$, $$Transition to Butterfly Guard Bottom$$);
insert into moves (id,name,reqstring) values (160, $$Triangle Choke from Butterfly Guard$$, $$Transition to Butterfly Guard Bottom$$);
insert into moves (id,name,reqstring) values (161, $$Transition to Half Guard Down Top$$, $$Transition to Butterfly Guard Bottom$$);
insert into moves (id,name,reqstring) values (162, $$Transition to Open Guard Top$$, $$Transition to Butterfly Guard Bottom$$);
insert into moves (id,name,reqstring) values (163, $$Transition to Side Control Top$$, $$Transition to Butterfly Guard Bottom$$);
insert into moves (id,name,reqstring) values (164, $$Slam to Open Guard Down Offense$$, $$None$$);
insert into moves (id,name,reqstring) values (165, $$Left Turn Off to Double Underhook Defense$$, $$None$$);
insert into moves (id,name,reqstring) values (166, $$Clinch to Body Lock Cage Offense$$, $$None$$);
insert into moves (id,name,reqstring) values (167, $$Pull Guard to Open Guard Down Defense$$, $$None$$);
insert into moves (id,name,reqstring) values (168, $$Suplex to Side Control Offense$$, $$None$$);
insert into moves (id,name,reqstring) values (169, $$Judo Hip Throw to Side Control Offense$$, $$None$$);
insert into moves (id,name,reqstring) values (170, $$Pummel to Double Underhook Offense$$, $$None$$);
insert into moves (id,name,reqstring) values (171, $$Pummel to Single Collar Tie$$, $$None$$);
insert into moves (id,name,reqstring) values (172, $$Clinch to Body Lock Offense$$, $$None$$);
insert into moves (id,name,reqstring) values (173, $$Pull Guard to Open Guard Down Defense$$, $$None$$);
insert into moves (id,name,reqstring) values (174, $$Suplex to Side Control Offense$$, $$None$$);
insert into moves (id,name,reqstring) values (175, $$Strike Catch to Armbar$$, $$None$$);
insert into moves (id,name,reqstring) values (176, $$Strike Catch to Kimura$$, $$None$$);
insert into moves (id,name,reqstring) values (177, $$Transition to Half Guard Down Bottom$$, $$None$$);
insert into moves (id,name,reqstring) values (178, $$Transition to Open Guard Bottom$$, $$None$$);
insert into moves (id,name,reqstring) values (179, $$Transition to Up/Down Bottom$$, $$None$$);
insert into moves (id,name,reqstring) values (180, $$Cage Transition to Half Guard Down Bottom$$, $$None$$);
insert into moves (id,name,reqstring) values (181, $$Kimura$$, $$None$$);
insert into moves (id,name,reqstring) values (182, $$Transition to Butterfly Guard Bottom$$, $$None$$);
insert into moves (id,name,reqstring) values (183, $$Transition to Open Guard Down Bottom$$, $$None$$);
insert into moves (id,name,reqstring) values (184, $$Transition to Up/Down Bottom$$, $$None$$);
insert into moves (id,name,reqstring) values (185, $$Americana from Half Guard Top$$, $$None$$);
insert into moves (id,name,reqstring) values (186, $$Kimura from Half Guard Top$$, $$None$$);
insert into moves (id,name,reqstring) values (187, $$Transition to Mount Down Top$$, $$None$$);
insert into moves (id,name,reqstring) values (188, $$Transition to Side Control Top$$, $$None$$);
insert into moves (id,name,reqstring) values (189, $$Americana from Half Guard Rocked Top$$, $$None$$);
insert into moves (id,name,reqstring) values (190, $$D'arce Choke$$, $$None$$);
insert into moves (id,name,reqstring) values (191, $$Kimura from Half Guard Top$$, $$None$$);
insert into moves (id,name,reqstring) values (192, $$Americana from Half Guard Top$$, $$None$$);
insert into moves (id,name,reqstring) values (193, $$Elbow$$, $$None$$);
insert into moves (id,name,reqstring) values (194, $$Hammer Fist$$, $$None$$);
insert into moves (id,name,reqstring) values (195, $$Kimura from Half Guard Top$$, $$None$$);
insert into moves (id,name,reqstring) values (196, $$Kneebar from Half Guard Top$$, $$None$$);
insert into moves (id,name,reqstring) values (197, $$Kneebar from Half Guard Top$$, $$None$$);
insert into moves (id,name,reqstring) values (198, $$Strong Hook$$, $$None$$);
insert into moves (id,name,reqstring) values (199, $$Toe Hold from Half Guard Top$$, $$None$$);
insert into moves (id,name,reqstring) values (200, $$Transition to Mount Down Top$$, $$None$$);
insert into moves (id,name,reqstring) values (201, $$Transition to Mount Top$$, $$None$$);
insert into moves (id,name,reqstring) values (202, $$Transition to Side Control Top$$, $$None$$);
insert into moves (id,name,reqstring) values (203, $$Transition to Half Guard Bottom$$, $$None$$);
insert into moves (id,name,reqstring) values (204, $$Transition to Mount Down Bottom$$, $$None$$);
insert into moves (id,name,reqstring) values (205, $$Cage Transition to Mount Down Top$$, $$None$$);
insert into moves (id,name,reqstring) values (206, $$Transition to Half Guard Down Bottom$$, $$None$$);
insert into moves (id,name,reqstring) values (207, $$Transition to Open Guard Down Top$$, $$Ground Grapple Offense 60$$);
insert into moves (id,name,reqstring) values (208, $$Arm Triangle Choke from Mount Top$$, $$None$$);
insert into moves (id,name,reqstring) values (209, $$Ground Buster from Mount Down Top$$, $$None$$);
insert into moves (id,name,reqstring) values (210, $$Transition to Open Guard Down Top$$, $$Ground Grapple Offense 60$$);
insert into moves (id,name,reqstring) values (211, $$Armbar from Mount Rocked Top$$, $$None$$);
insert into moves (id,name,reqstring) values (212, $$Arm Triangle Choke from Mount Top$$, $$None$$);
insert into moves (id,name,reqstring) values (213, $$Armbar from Mount Top$$, $$None$$);
insert into moves (id,name,reqstring) values (214, $$Elbow$$, $$None$$);
insert into moves (id,name,reqstring) values (215, $$Strong Hook$$, $$None$$);
insert into moves (id,name,reqstring) values (216, $$Rear Leg Knee$$, $$None$$);
insert into moves (id,name,reqstring) values (217, $$Strong Knee$$, $$None$$);
insert into moves (id,name,reqstring) values (218, $$Pummel to Muay Thai Clinch Offense$$, $$None$$);
insert into moves (id,name,reqstring) values (219, $$Pummel to Over/Under Hook$$, $$None$$);
insert into moves (id,name,reqstring) values (220, $$Arcing Elbow$$, $$None$$);
insert into moves (id,name,reqstring) values (221, $$Knee$$, $$None$$);
insert into moves (id,name,reqstring) values (222, $$Knee to Body$$, $$None$$);
insert into moves (id,name,reqstring) values (223, $$Pull Guard to Open Guard Down Defense$$, $$None$$);
insert into moves (id,name,reqstring) values (224, $$Rear Leg Knee$$, $$None$$);
insert into moves (id,name,reqstring) values (225, $$Strong Knee$$, $$None$$);
insert into moves (id,name,reqstring) values (226, $$Uppercut$$, $$None$$);
insert into moves (id,name,reqstring) values (227, $$Armbar from North/South Top$$, $$None$$);
insert into moves (id,name,reqstring) values (228, $$North/South Choke from North/South Top$$, $$None$$);
insert into moves (id,name,reqstring) values (229, $$Transition to Mount Down Top$$, $$None$$);
insert into moves (id,name,reqstring) values (230, $$Strike Catch to Armbar$$, $$None$$);
insert into moves (id,name,reqstring) values (231, $$Strike Catch to Kimura$$, $$None$$);
insert into moves (id,name,reqstring) values (232, $$Strike Catch to Omoplata$$, $$Submission Offense 60$$);
insert into moves (id,name,reqstring) values (233, $$Strike Catch to Triangle Choke$$, $$None$$);
insert into moves (id,name,reqstring) values (234, $$Transition to Open Guard Down Bottom$$, $$None$$);
insert into moves (id,name,reqstring) values (235, $$Transition to Up/Down Bottom$$, $$None$$);
insert into moves (id,name,reqstring) values (236, $$Kimura$$, $$None$$);
insert into moves (id,name,reqstring) values (237, $$Omoplata$$, $$Submission Offense 60$$);
insert into moves (id,name,reqstring) values (238, $$Transition to Rubber Guard Down Bottom$$, $$None$$);
insert into moves (id,name,reqstring) values (239, $$Transition to Up/Down Bottom$$, $$None$$);
insert into moves (id,name,reqstring) values (240, $$Triangle Choke$$, $$None$$);
insert into moves (id,name,reqstring) values (241, $$Transition to Half Guard Down Top$$, $$None$$);
insert into moves (id,name,reqstring) values (242, $$Transition to Side Control Top$$, $$None$$);
insert into moves (id,name,reqstring) values (243, $$Achilles Lock$$, $$None$$);
insert into moves (id,name,reqstring) values (244, $$Heel Hook$$, $$None$$);
insert into moves (id,name,reqstring) values (245, $$Kneebar$$, $$None$$);
insert into moves (id,name,reqstring) values (246, $$Toe Hold$$, $$None$$);
insert into moves (id,name,reqstring) values (247, $$Achilles Lock from Open Guard Top$$, $$None$$);
insert into moves (id,name,reqstring) values (248, $$Elbow$$, $$None$$);
insert into moves (id,name,reqstring) values (249, $$Heel Hook from Open Guard Top$$, $$None$$);
insert into moves (id,name,reqstring) values (250, $$Kneebar from Open Guard Top$$, $$None$$);
insert into moves (id,name,reqstring) values (251, $$Strong Hook$$, $$None$$);
insert into moves (id,name,reqstring) values (252, $$Toe Hold from Open Guard Top$$, $$None$$);
insert into moves (id,name,reqstring) values (253, $$Transition to Half Guard Down Top$$, $$None$$);
insert into moves (id,name,reqstring) values (254, $$Transition to Half Guard Top$$, $$None$$);
insert into moves (id,name,reqstring) values (255, $$Transition to Side Control Top$$, $$None$$);
insert into moves (id,name,reqstring) values (256, $$Ouchi Gari to Open Guard Down Offense$$, $$Suplex to Side Control Offense$$);
insert into moves (id,name,reqstring) values (257, $$Pummel to Double Underhook Cage Offense$$, $$None$$);
insert into moves (id,name,reqstring) values (258, $$Takedown to Half Guard Down Offense$$, $$Suplex to Side Control Offense$$);
insert into moves (id,name,reqstring) values (259, $$Hip Throw to Side Control Offense$$, $$Suplex to Side Control Offense$$);
insert into moves (id,name,reqstring) values (260, $$Pull Guard to Open Guard Down Defense$$, $$Suplex to Side Control Offense$$);
insert into moves (id,name,reqstring) values (261, $$Pummel to Double Underhook Offense$$, $$None$$);
insert into moves (id,name,reqstring) values (262, $$Gogoplata from Rubber Guard Bottom$$, $$Transition to Rubber Guard Down Bottom and Submission Offense 70$$);
insert into moves (id,name,reqstring) values (263, $$Omoplata from Rubber Guard Bottom$$, $$Transition to Rubber Guard Down Bottom and Submission Offense 60$$);
insert into moves (id,name,reqstring) values (264, $$Triangle Choke from Rubber Guard Bottom$$, $$Transition to Rubber Guard Down Bottom$$);
insert into moves (id,name,reqstring) values (265, $$Transition to Half Guard Down Top$$, $$Transition to Rubber Guard Down Bottom$$);
insert into moves (id,name,reqstring) values (266, $$Transition to Open Guard Top$$, $$Transition to Rubber Guard Down Bottom$$);
insert into moves (id,name,reqstring) values (267, $$Armbar from Salaverry Top$$, $$Transition to Salaverry Top$$);
insert into moves (id,name,reqstring) values (268, $$Transition to Both Standing$$, $$Transition to Salaverry Top$$);
insert into moves (id,name,reqstring) values (269, $$Americana from Side Control Top$$, $$Transition to Salaverry Top$$);
insert into moves (id,name,reqstring) values (270, $$Elbow$$, $$Transition to Salaverry Top$$);
insert into moves (id,name,reqstring) values (271, $$Transition to Mount Top$$, $$Transition to Salaverry Top$$);
insert into moves (id,name,reqstring) values (272, $$Cage Transition to Side Control Top$$, $$None$$);
insert into moves (id,name,reqstring) values (273, $$Transition to Both Standing$$, $$None$$);
insert into moves (id,name,reqstring) values (274, $$Transition to Butterfly Guard Bottom$$, $$None$$);
insert into moves (id,name,reqstring) values (275, $$Transition to Half Guard Down Bottom$$, $$None$$);
insert into moves (id,name,reqstring) values (276, $$Transition to Open Guard Down Bottom$$, $$None$$);
insert into moves (id,name,reqstring) values (277, $$Americana from Side Control Top$$, $$None$$);
insert into moves (id,name,reqstring) values (278, $$Armbar from Side Control Rocked Top$$, $$None$$);
insert into moves (id,name,reqstring) values (279, $$Americana from Side Control Top$$, $$None$$);
insert into moves (id,name,reqstring) values (280, $$Arm Triangle Choke$$, $$None$$);
insert into moves (id,name,reqstring) values (281, $$Elbow$$, $$None$$);
insert into moves (id,name,reqstring) values (282, $$Kimura from Side Control Top$$, $$None$$);
insert into moves (id,name,reqstring) values (283, $$Strong Left Knee to Abdomen$$, $$None$$);
insert into moves (id,name,reqstring) values (284, $$Strong Right Knee to Abdomen$$, $$None$$);
insert into moves (id,name,reqstring) values (285, $$Transition to Mount Down Top$$, $$None$$);
insert into moves (id,name,reqstring) values (286, $$Transition to Mount Top$$, $$None$$);
insert into moves (id,name,reqstring) values (287, $$Transition to Salaverry Top$$, $$Ground Grapple Offense of 60$$);
insert into moves (id,name,reqstring) values (288, $$Crushing Knee$$, $$None$$);
insert into moves (id,name,reqstring) values (289, $$Downward Arcing Elbow$$, $$None$$);
insert into moves (id,name,reqstring) values (290, $$Strong Hook$$, $$None$$);
insert into moves (id,name,reqstring) values (291, $$Strong Knee to Abdomen$$, $$None$$);
insert into moves (id,name,reqstring) values (292, $$Strong Uppercut$$, $$None$$);
insert into moves (id,name,reqstring) values (293, $$Uppercut to Body$$, $$None$$);
insert into moves (id,name,reqstring) values (294, $$Pull Guard to Open Guard Down Defense$$, $$None$$);
insert into moves (id,name,reqstring) values (295, $$Strong Hook$$, $$None$$);
insert into moves (id,name,reqstring) values (296, $$Uppercut$$, $$None$$);
insert into moves (id,name,reqstring) values (297, $$Slam to Open Guard Down Offense$$, $$None$$);
insert into moves (id,name,reqstring) values (298, $$Slam to Side Control Offense$$, $$None$$);
insert into moves (id,name,reqstring) values (299, $$Transition to Both Standing$$, $$None$$);
insert into moves (id,name,reqstring) values (300, $$Transition to Open Guard Down Bottom$$, $$None$$);
insert into moves (id,name,reqstring) values (301, $$Guillotine Choke from Sprawl Rocked$$, $$None$$);
insert into moves (id,name,reqstring) values (302, $$Anaconda Choke from Sprawl Top$$, $$None$$);
insert into moves (id,name,reqstring) values (303, $$Guillotine Choke from Sprawl Top$$, $$None$$);
insert into moves (id,name,reqstring) values (304, $$Peruvian Neck Tie from Sprawl Top$$, $$Submission Offense of 60$$);
insert into moves (id,name,reqstring) values (305, $$Strong Hook$$, $$None$$);
insert into moves (id,name,reqstring) values (306, $$Transition to Back Mount Top$$, $$None$$);
insert into moves (id,name,reqstring) values (307, $$Left Superman Punch$$, $$None$$);
insert into moves (id,name,reqstring) values (308, $$Right Superman Punch$$, $$None$$);
insert into moves (id,name,reqstring) values (309, $$Kneebar from Up/Down Near Bottom$$, $$None$$);
insert into moves (id,name,reqstring) values (310, $$Up-Kick$$, $$None$$);
insert into moves (id,name,reqstring) values (311, $$Achilles Lock from Up/Down Near Top$$, $$None$$);
insert into moves (id,name,reqstring) values (312, $$Heel Hook from Up/Down Near Top$$, $$None$$);
insert into moves (id,name,reqstring) values (313, $$Kneebar from Up/Down Near Top$$, $$None$$);
insert into moves (id,name,reqstring) values (314, $$Left Axe Kick to Body$$, $$None$$);
insert into moves (id,name,reqstring) values (315, $$Left Superman Punch$$, $$None$$);
insert into moves (id,name,reqstring) values (316, $$Right Superman Punch$$, $$None$$);
insert into moves (id,name,reqstring) values (317, $$Toe Hold from Up/Down Near Top$$, $$None$$);
