update fighters set country=1 where countrystr=$$Armenia$$;
update fighters set country=2 where countrystr=$$Australia$$;
update fighters set country=3 where countrystr=$$Bahamas$$;
update fighters set country=4 where countrystr=$$Belarus$$;
update fighters set country=5 where countrystr=$$Brazil$$;
update fighters set country=6 where countrystr=$$Bulgaria$$;
update fighters set country=7 where countrystr=$$Canada$$;
update fighters set country=8 where countrystr=$$China$$;
update fighters set country=9 where countrystr=$$Croatia$$;
update fighters set country=10 where countrystr=$$Cuba$$;
update fighters set country=11 where countrystr=$$Cyprus$$;
update fighters set country=12 where countrystr=$$Czech Republic$$;
update fighters set country=13 where countrystr=$$Denmark$$;
update fighters set country=14 where countrystr=$$El Salvador$$;
update fighters set country=15 where countrystr=$$England$$;
update fighters set country=16 where countrystr=$$France$$;
update fighters set country=17 where countrystr=$$Germany$$;
update fighters set country=18 where countrystr=$$Haiti$$;
update fighters set country=19 where countrystr=$$Iran$$;
update fighters set country=20 where countrystr=$$Italy$$;
update fighters set country=21 where countrystr=$$Japan$$;
update fighters set country=22 where countrystr=$$Netherlands$$;
update fighters set country=23 where countrystr=$$New Zealand$$;
update fighters set country=24 where countrystr=$$Nigeria$$;
update fighters set country=25 where countrystr=$$Poland$$;
update fighters set country=26 where countrystr=$$Russia$$;
update fighters set country=27 where countrystr=$$South Korea$$;
update fighters set country=28 where countrystr=$$Sweden$$;
update fighters set country=29 where countrystr=$$United States of America$$;
