insert into positions (id, name) values (1, 'Back Clinch Cage Offense');
insert into positions (id, name) values (2, 'Back Clinch Defense');
insert into positions (id, name) values (3, 'Back Clinch Offense');
insert into positions (id, name) values (4, 'Back Mount Bottom');
insert into positions (id, name) values (5, 'Back Mount Face Up Top');
insert into positions (id, name) values (6, 'Back Mount Rocked Top');
insert into positions (id, name) values (7, 'Back Mount Top');
insert into positions (id, name) values (8, 'Back Side Control Bottom');
insert into positions (id, name) values (9, 'Back Side Control Rocked Top');
insert into positions (id, name) values (10, 'Back Side Control Top');
insert into positions (id, name) values (11, 'Body Lock Cage Offense');
insert into positions (id, name) values (12, 'Body Lock Defense');
insert into positions (id, name) values (13, 'Body Lock Offense');
insert into positions (id, name) values (14, 'Both Standing Clinch Range');
insert into positions (id, name) values (15, 'Both Standing Striking Range');
insert into positions (id, name) values (16, 'Butterfly Guard Bottom');
insert into positions (id, name) values (17, 'Butterfly Guard Top');
insert into positions (id, name) values (18, 'Double Leg Clinch Cage Offense');
insert into positions (id, name) values (19, 'Double Underhook Cage Defense');
insert into positions (id, name) values (20, 'Double Underhook Cage Offense');
insert into positions (id, name) values (21, 'Double Underhook Defense');
insert into positions (id, name) values (22, 'Double Underhook Offense');
insert into positions (id, name) values (23, 'Half Guard Bottom');
insert into positions (id, name) values (24, 'Half Guard Down Bottom');
insert into positions (id, name) values (25, 'Half Guard Down Top');
insert into positions (id, name) values (26, 'Half Guard Rocked Top');
insert into positions (id, name) values (27, 'Half Guard Top');
insert into positions (id, name) values (28, 'Mount Bottom');
insert into positions (id, name) values (29, 'Mount Down Bottom');
insert into positions (id, name) values (30, 'Mount Down Top');
insert into positions (id, name) values (31, 'Mount Rocked Top');
insert into positions (id, name) values (32, 'Mount Top');
insert into positions (id, name) values (33, 'Muay Thai Clinch Cage Offense');
insert into positions (id, name) values (34, 'Muay Thai Clinch Defense');
insert into positions (id, name) values (35, 'Muay Thai Clinch Offense');
insert into positions (id, name) values (36, 'North/South Top');
insert into positions (id, name) values (37, 'Open Guard Bottom');
insert into positions (id, name) values (38, 'Open Guard Down Bottom');
insert into positions (id, name) values (39, 'Open Guard Down Top');
insert into positions (id, name) values (40, 'Open Guard Rocked Top');
insert into positions (id, name) values (41, 'Open Guard Top');
insert into positions (id, name) values (42, 'Over/Under Hook Cage Offense');
insert into positions (id, name) values (43, 'Over/Under Hook Offense');
insert into positions (id, name) values (44, 'Rubber Guard Bottom');
insert into positions (id, name) values (45, 'Rubber Guard Top');
insert into positions (id, name) values (46, 'Sallaverry Bottom');
insert into positions (id, name) values (47, 'Sallaverry Top');
insert into positions (id, name) values (48, 'Side Control Bottom');
insert into positions (id, name) values (49, 'Side Control Rocked Top');
insert into positions (id, name) values (50, 'Side Control Top');
insert into positions (id, name) values (51, 'Single Collar Tie Cage Offense');
insert into positions (id, name) values (52, 'Single Collar Tie Offense');
insert into positions (id, name) values (53, 'Single Leg Clinch Cage Offense');
insert into positions (id, name) values (54, 'Sprawl Bottom');
insert into positions (id, name) values (55, 'Sprawl Rocked Top');
insert into positions (id, name) values (56, 'Sprawl Top');
insert into positions (id, name) values (57, 'Up/Down Far Top');
insert into positions (id, name) values (58, 'Up/Down Near Bottom');
insert into positions (id, name) values (59, 'Up/Down Near Top');
